from __future__ import annotations

from enum import StrEnum


class HealthState(StrEnum):
    STARTING = "STARTING"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"
    STOPPING = "STOPPING"


class HostState(StrEnum):
    UNKNOWN = "UNKNOWN"
    STARTING = "STARTING"
    NORMAL = "NORMAL"
    SCHEDULE_BLOCKED = "SCHEDULE_BLOCKED"
    DISABLED = "DISABLED"
    MAINTENANCE = "MAINTENANCE"
    WARNING = "WARNING"
    FAULT = "FAULT"
    RECOVERY = "RECOVERY"
    OFFLINE = "OFFLINE"


class OperationStage(StrEnum):
    REQUESTED = "REQUESTED"
    VALIDATING = "VALIDATING"
    PLANNING = "PLANNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    APPLYING = "APPLYING"
    VERIFYING = "VERIFYING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ROLLING_BACK = "ROLLING_BACK"
    ROLLED_BACK = "ROLLED_BACK"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"
    CANCELLED = "CANCELLED"
    TIMED_OUT = "TIMED_OUT"


class AlarmSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    FAULT = "FAULT"
    CRITICAL = "CRITICAL"


class AccessDecision(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"


class ApplyMode(StrEnum):
    IMMEDIATE = "IMMEDIATE"
    SCHEDULED = "SCHEDULED"
    RELOAD = "RELOAD"
    RESTART_REQUIRED = "RESTART_REQUIRED"
    MAINTENANCE_REQUIRED = "MAINTENANCE_REQUIRED"
